import './globals.css'
import type { Metadata } from 'next'
import NavBar from './home/navBar/navBar'
import { Inter, Secular_One } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],  
  variable: '--font-inter',
})
const secular_one = Secular_One({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-secular-one',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="veterinaria">
      <body className={`${inter.variable} ${secular_one.variable}`}>
        <div className="sticky top-0 z-10 ">
          <NavBar />
        </div>
        {children}
      </body>
    </html>
  )
}
